### ISSUE TITLE
Issue loading plugin, says expecting close brace or comma. Can't figure out where.

### ISSUE THREAD

**Issue by Jaded-Avaritia** [SkyFire55/daily-rewards#13]
https://hastebin.com/uzobayonis.cs

> 14.11 23:05:45 [Server] Server thread/INFO [dailyrewards]: configurate.typesafe.config.ConfigException$Parse: Reader: 1: Expecting close brace } or a comma, got end of file
> 14.11 23:05:45 [Server] Server thread/ERROR [Sponge]: Could not pass FMLServerStartedEvent to Plugin{id=dailyrewards, name=DailyRewards, description=Plugin for rewarding players for every day logging it!, source=./mods/DailyRewards-api7-1.3.2.jar}
> 14.11 23:05:45 [Server] INFO java.lang.NullPointerException: null
> 14.11 23:05:45 [Server] INFO at ru.skyfire.zeta.dailyrewards.serializers.RewardDeserializer.<init>(RewardDeserializer.java:25) ~[RewardDeserializer.class:?]
> 14.11 23:05:45 [Server] INFO at ru.skyfire.zeta.dailyrewards.DailyRewards.onServerStart(DailyRewards.java:67) ~[DailyRewards.class:?]
> 14.11 23:05:45 [Server] INFO at org.spongepowered.common.event.listener.GameStartedServerEventListener_DailyRewards_onServerStart12.handle(Unknown Source) ~[?:?]

I see that it says expecting a close brace or comma, but I cannot figure out where because it all looks closed to me.

**Comment by VimbaTheFish** [comment]
I just copied your config and pasted it on my server:
![default](https://user-images.githubusercontent.com/22179405/48548216-7e595400-e8dd-11e8-9d51-e3e9f56cca5b.png)
Try to generate again new config, check it and then paste yours. Let me know if it doesn't help.

**Comment by Jaded-Avaritia** [comment]
> 15.11 10:42:28 [Server] Server thread/INFO [dailyrewards]: configurate.typesafe.config.ConfigException$Parse: Reader: 1: Expecting close brace } or a comma, got end of file
> 15.11 10:42:28 [Server] Server thread/ERROR [Sponge]: Could not pass FMLServerStartedEvent to Plugin{id=dailyrewards, name=DailyRewards, description=Plugin for rewarding players for every day logging it!, source=./mods/DailyRewards-api7-1.3.2.jar}
> 15.11 10:42:28 [Server] INFO java.lang.NullPointerException: null
> 15.11 10:42:28 [Server] INFO at ru.skyfire.zeta.dailyrewards.serializers.RewardDeserializer.<init>(RewardDeserializer.java:25) ~[RewardDeserializer.class:?]
> 15.11 10:42:28 [Server] INFO at ru.skyfire.zeta.dailyrewards.DailyRewards.onServerStart(DailyRewards.java:67) ~[DailyRewards.class:?]

Still getting the same issue when I regenerate it then add it in or copy it over. But it works with the default config.
Figure I'd include a list of mods installed in case one of them could be causing the issue.

![screenshot_52](https://user-images.githubusercontent.com/4406708/48564101-c3708c80-e8c3-11e8-80f6-7d3944f71ccd.png)

**Comment by VimbaTheFish** [comment]
Try to add days one by one and reaload plugin every update. It will show what day cause troubles.

**Comment by Jaded-Avaritia** [comment]
[text.txt](https://github.com/SkyFire55/daily-rewards/files/2598178/text.txt)

Sorry, power was out this weekend.

I add one day, and I get the same error.

**Comment by VimbaTheFish** [comment]
Can u send me the config file?

**Comment by Jaded-Avaritia** [comment]
[dailyrewardsfourdays.txt](https://github.com/SkyFire55/daily-rewards/files/2600216/dailyrewardsfourdays.txt)

When I have time today after work, I'll try running the plugin alone and slowly adding other plugins to see if one of them if effecting it.

I tried turning debug on and that didn't help either.

**Comment by VimbaTheFish** [comment]
![default](https://user-images.githubusercontent.com/22179405/48803332-aeac5280-ed22-11e8-864c-b58a226508ad.png)

I really don't understand, it's some sort of magic. That's just copy of your config.

U know, try to remove the first and the last brackets. And don't delete other plugins and mods, that's not their fault.
Does usual editing of default config (i mean item icon and reward) works?

**Comment by Jaded-Avaritia** [comment]
Removing the brackets from a config gives me
> 20.11 23:21:56 [Server] Server thread/INFO [dailyrewards]: Alarm! Can't read rewards from config! Is it empty?

Changed the icon item for day one to Minecraft:Coal
![screenshot_71](https://user-images.githubusercontent.com/4406708/48819204-be289d00-ed1c-11e8-898d-8c0f5f4bfd9d.png)
Okay that works.

![screenshot_72](https://user-images.githubusercontent.com/4406708/48819247-03e56580-ed1d-11e8-9963-deaa952aeb79.png)
Changing the reward from 4 diamond to 4 wool works

-----

So I can essentially change the rewards and info (Including pixelmon items) for the existing 3 default days, but if I add anymore days my server has a hissy fit loading anything in. I added another day with edited rewards and icon, and after a reload it wouldn't recognize the new config.

> 20.11 23:34:48 [Server] Server thread/INFO [nucleus]: Jaedeite ran the command: /dr reload
> 20.11 23:34:50 [Server] Server thread/INFO [nucleus]: Jaedeite ran the command: /dr 
> 20.11 23:34:53 [Server] Server thread/INFO [nucleus]: Jaedeite ran the command: /daily 
> 20.11 23:34:57 [Server] Server thread/INFO [nucleus]: Jaedeite ran the command: /dr help
> 20.11 23:35:01 [Server] Server thread/INFO [nucleus]: Jaedeite ran the command: /dr show
> 20.11 23:35:09 [Server] Server thread/INFO [nucleus]: Jaedeite ran the command: /dr take
> 20.11 23:36:30 [Server] Server thread/INFO [nucleus]: Jaedeite ran the command: /dr reload
> 20.11 23:36:31 [Server] Server thread/INFO [nucleus]: Jaedeite ran the command: /daily 
> 20.11 23:36:34 [Server] Server thread/INFO [nucleus]: Jaedeite ran the command: /dr show
> 20.11 23:38:09 [Server] Server thread/INFO [nucleus]: Jaedeite ran the command: /daily reward
> 20.11 23:38:15 [Server] Server thread/INFO [nucleus]: Jaedeite ran the command: /dr reload
> 20.11 23:38:15 [Server] Server thread/INFO [dailyrewards]: configurate.typesafe.config.ConfigException$Parse: Reader: 1: Expecting close brace } or a comma, got end of file
> 20.11 23:38:18 [Server] Server thread/INFO [nucleus]: Jaedeite ran the command: /dr show
> 20.11 23:39:52 [Server] Server thread/INFO [nucleus]: Jaedeite ran the command: /dr reload
> 20.11 23:39:52 [Server] Server thread/INFO [dailyrewards]: configurate.typesafe.config.ConfigException$Parse: Reader: 1: Expecting close brace } or a comma, got end of file
> 20.11 23:39:53 [Server] Server thread/INFO [nucleus]: Jaedeite ran the command: /dr show
> 20.11 23:40:02 [Server] Server thread/INFO [nucleus]: Jaedeite ran the command: /dr take

**EDIT:**
I'm starting to think it's an issue with my version of sponge. I uninstalled everything but sponge and pixelmon on a homehosted to see if dailies will load, and it still won't.

**EDIT TWO:**
Updated the sponge to recommended then newest, but it still won't load the plugin with the edited config.

![screenshot_73](https://user-images.githubusercontent.com/4406708/48821278-93dbdd00-ed26-11e8-90aa-858059587a31.png)

**Comment by VimbaTheFish** [comment]
Try to edit this one:

https://pastebin.com/jCYBe4b9

Default one without first and last brackets. Check this one firstly and then edit.

**Comment by Jaded-Avaritia** [comment]
Sorry for the late response. Thanksgiving then I was sick.

It works, though /dr show gives me this error at the bottom

![screenshot_76](https://user-images.githubusercontent.com/4406708/48975153-b75d9b00-f038-11e8-8242-e78207efb967.png)

> 24.11 22:36:11 [Server] Server thread/ERROR [Sponge]: Error occurred while executing command 'dr show' for source EntityPlayerMP['Jaedeite'/407, l='world', x=-5906.76, y=49.00, z=7582.69]: null
> 24.11 22:36:11 [Server] INFO java.lang.NullPointerException: null
> 24.11 22:36:11 [Server] INFO at ru.skyfire.zeta.dailyrewards.util.ItemUtil.parseItem(ItemUtil.java:154) ~[ItemUtil.class:?]
> 24.11 22:36:11 [Server] INFO at ru.skyfire.zeta.dailyrewards.util.GuiUtil.showRewards(GuiUtil.java:44) ~[GuiUtil.class:?]
> 24.11 22:36:11 [Server] INFO at ru.skyfire.zeta.dailyrewards.commands.CmdDailyShow.execute(CmdDailyShow.java:19) ~[CmdDailyShow.class:?]
> 24.11 22:36:11 [Server] INFO at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:255) ~[ChildCommandElementExecutor.class:1.12.2-2705-7.1.0-BETA-3361]
> 24.11 22:36:11 [Server] INFO at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388) ~[CommandSpec.class:1.12.2-2705-7.1.0-BETA-3361]
> 24.11 22:36:11 [Server] INFO at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:341) ~[SimpleDispatcher.class:1.12.2-2705-7.1.0-BETA-3361]
> 24.11 22:36:11 [Server] INFO at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:329) [SpongeCommandManager.class:1.12.2-2705-7.1.0-BETA-3361]
> 24.11 22:36:11 [Server] INFO at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) [dh.class:?]
> 24.11 22:36:11 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:960) [pa.class:?]
> 24.11 22:36:11 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:939) [pa.class:?]
> 24.11 22:36:11 [Server] INFO at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
> 24.11 22:36:11 [Server] INFO at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
> 24.11 22:36:11 [Server] INFO at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:92) [PacketUtil.class:1.12.2-2705-7.1.0-BETA-3361]
> 24.11 22:36:11 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zle000(SourceFile:539) [hv$1.class:?]
> 24.11 22:36:11 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
> 24.11 22:36:11 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
> 24.11 22:36:11 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
> 24.11 22:36:11 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
> 24.11 22:36:11 [Server] INFO at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:293) [SpongeImplHooks.class:1.12.2-2705-7.1.0-BETA-3361]
> 24.11 22:36:11 [Server] INFO at net.minecraft.server.MinecraftServer.redirect$onRun$zjj000(MinecraftServer.java:3963) [MinecraftServer.class:?]
> 24.11 22:36:11 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
> 24.11 22:36:11 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
> 24.11 22:36:11 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
> 24.11 22:36:11 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
> 24.11 22:36:11 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]

The plugin lets me claim rewards, but it tells me 'There is no reward today, but keep going!" despite a reward being set.

**Comment by VimbaTheFish** [comment]
Are u sure there is no mistake in materialname of item u use in reward icon? Or is it uneddited config?

**Comment by SkyFire55** [comment]
Are u sure there is no mistake in materialname of item u use in reward icon? Or is it uneddited config?

**Comment by Jaded-Avaritia** [comment]
It's happening in the unedited config you gave me and when I try to edit the config.

**Comment by VimbaTheFish** [comment]
I still remember, sorry, had some buisness to do. Investigating ^^

**Comment by Jaded-Avaritia** [comment]
Okay! Good luck and thank you.

**Comment by VimbaTheFish** [comment]
Try new version with generated again config file.

**Comment by Jaded-Avaritia** [comment]
> 09.12 19:46:42 [Server] Server thread/INFO [nucleus]: Jaedeite ran the command: /dr show
> 09.12 19:46:42 [Server] Server thread/ERROR [Sponge]: Error occurred while executing command 'dr show' for source EntityPlayerMP['Jaedeite'/426, l='world', x=12873.70, y=112.00, z=14285.30]: null
> 09.12 19:46:42 [Server] INFO java.lang.NullPointerException: null
> 09.12 19:46:42 [Server] INFO at ru.skyfire.zeta.dailyrewards.util.ItemUtil.parseItem(ItemUtil.java:156) ~[ItemUtil.class:?]
> 09.12 19:46:42 [Server] INFO at ru.skyfire.zeta.dailyrewards.util.GuiUtil.showRewards(GuiUtil.java:44) ~[GuiUtil.class:?]
> 09.12 19:46:42 [Server] INFO at ru.skyfire.zeta.dailyrewards.commands.CmdDailyShow.execute(CmdDailyShow.java:19) ~[CmdDailyShow.class:?]
> 09.12 19:46:42 [Server] INFO at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:255) ~[ChildCommandElementExecutor.class:1.12.2-2768-7.1.5-RC3509]
> 09.12 19:46:42 [Server] INFO at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388) ~[CommandSpec.class:1.12.2-2768-7.1.5-RC3509]
> 09.12 19:46:42 [Server] INFO at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:340) ~[SimpleDispatcher.class:1.12.2-2768-7.1.5-RC3509]
> 09.12 19:46:42 [Server] INFO at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:334) [SpongeCommandManager.class:1.12.2-2768-7.1.5-RC3509]
> 09.12 19:46:42 [Server] INFO at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) [dh.class:?]
> 09.12 19:46:42 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:960) [pa.class:?]
> 09.12 19:46:42 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:939) [pa.class:?]
> 09.12 19:46:42 [Server] INFO at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
> 09.12 19:46:42 [Server] INFO at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
> 09.12 19:46:42 [Server] INFO at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:193) [PacketPhaseUtil.class:1.12.2-2768-7.1.5-RC3509]
> 09.12 19:46:42 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zlh000(SourceFile:539) [hv$1.class:?]
> 09.12 19:46:42 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
> 09.12 19:46:42 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
> 09.12 19:46:42 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
> 09.12 19:46:42 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
> 09.12 19:46:42 [Server] INFO at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:297) [SpongeImplHooks.class:1.12.2-2768-7.1.5-RC3509]
> 09.12 19:46:42 [Server] INFO at net.minecraft.server.MinecraftServer.redirect$onRun$zjl000(MinecraftServer.java:3970) [MinecraftServer.class:?]
> 09.12 19:46:42 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
> 09.12 19:46:42 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
> 09.12 19:46:42 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
> 09.12 19:46:42 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
> 09.12 19:46:42 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]

It loads with the default config but not edited still.

**Comment by VimbaTheFish** [comment]
I don't understand what's wrong with your server.
Try to load this plugin on the fresh server wothout any mods and let me know about results.

**Comment by Jaded-Avaritia** [comment]
I did that already 27 days ago (So... November 20th?) and posted about it.

**Comment by VimbaTheFish** [comment]
I mean with latest jar version, which was releazed after that. If it will send an error, send it here, i'll try to figure it out.
As last time, clear spongeforge and DailyRewards.

**Comment by Jaded-Avaritia** [comment]
I got so busy with work and honestly forgot about this completely

So, my test server only has this
![screenshot_1](https://user-images.githubusercontent.com/4406708/51885854-65e4cb80-235b-11e9-86ac-4bc6a4a43f1a.png)

It seems to run fine with just the default of course like usual.

Add a fourth day, copy pasting day 3 and changing the '3' to '4'.

Relaunch server

![screenshot_3](https://user-images.githubusercontent.com/4406708/51886130-73e71c00-235c-11e9-9086-f34627ca442f.png)

So it works on a fresh copy of a test server. But when I used the same sponge and pixelmon I'm still getting the same error on my server with all these mods installed

![screenshot_4](https://user-images.githubusercontent.com/4406708/51886163-9d07ac80-235c-11e9-9fec-23ad3965b22d.png)

I'll try some trial and error to see what could be effecting it.

EDIT:
So, all the mods moved over and it still works. So it's not a mod issue. However, this makes me think it's an issue with one of my config settings effecting the plugin.

> [00:45:10] [Server thread/ERROR] [Sponge]: The Scheduler tried to run the task dailyrewards-S-21 owned by Plugin{id=dailyrewards, name=DailyRewards, description=Plugin for rewarding players for every day logging it!, source=.\mods\DailyRewards-api7-1.3.3 (1).jar}, but an error occured.
> java.lang.NullPointerException: null
>         at ru.skyfire.zeta.dailyrewards.util.ItemUtil.parseItem(ItemUtil.java:156) ~[ItemUtil.class:?]
>         at ru.skyfire.zeta.dailyrewards.util.GuiUtil.showRewards(GuiUtil.java:44) ~[GuiUtil.class:?]
>         at ru.skyfire.zeta.dailyrewards.listeners.Listeners.lambda$onPlayerConnect$0(Listeners.java:43) ~[Listeners.class:?]
>         at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:192) ~[SchedulerBase.class:1.12.2-2768-7.1.5-RC3542]
>         at org.spongepowered.common.scheduler.SyncScheduler.executeTaskRunnable(SyncScheduler.java:74) ~[SyncScheduler.class:1.12.2-2768-7.1.5-RC3542]
>         at org.spongepowered.common.scheduler.SchedulerBase.startTask(SchedulerBase.java:183) ~[SchedulerBase.class:1.12.2-2768-7.1.5-RC3542]
>         at org.spongepowered.common.scheduler.SchedulerBase.processTask(SchedulerBase.java:169) ~[SchedulerBase.class:1.12.2-2768-7.1.5-RC3542]
>         at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(Unknown Source) [?:1.8.0_191]
>         at org.spongepowered.common.scheduler.SchedulerBase.runTick(SchedulerBase.java:112) [SchedulerBase.class:1.12.2-2768-7.1.5-RC3542]
>         at org.spongepowered.common.scheduler.SyncScheduler.tick(SyncScheduler.java:47) [SyncScheduler.class:1.12.2-2768-7.1.5-RC3542]
>         at org.spongepowered.common.scheduler.SpongeScheduler.tickSyncScheduler(SpongeScheduler.java:189) [SpongeScheduler.class:1.12.2-2768-7.1.5-RC3542]
>         at org.spongepowered.mod.SpongeMod.onTick(SpongeMod.java:353) [SpongeMod.class:1.12.2-2768-7.1.5-RC3542]
>         at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_26_SpongeMod_onTick_ServerTickEvent.invoke(.dynamic) [?:?]
>         at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
>         at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:747) [EventBus.class:?]
>         at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:697) [EventBus.class:?]
>         at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:279) [FMLCommonHandler.class:?]
>         at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657) [MinecraftServer.class:?]
>         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
>         at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]

EDIT: I brought all my configs over and the plugin stopped working ASAP. I'm going to delete them and let them regen to find the one that is the fault.

EDIT: Test one, deleted all the .cfg out of the folders and let them regen. Plugin still doesn't work.

Next tried sts to worldedit. Plugin still didn't work.

EDIT: Sponge to nucleus next. Still wouldn't work.

Minereset to GTS is next. Still didn't fix it.

EDIT
GTS to Daily rewards
Daily rewards works when reset
Added in day 4 again.
Now it's working.
Added in GTS to enjin-minecraft-plugin to test if any of these effect it.

EDIT: 
Okay so... it's working now when I dragged the config over?????? Uh. Huh. Weird.

EDIT:
Dude I... I don't know what I changed.
![screenshot_5](https://user-images.githubusercontent.com/4406708/51887778-e955eb00-2362-11e9-9fbb-4926622443d4.png)

**Comment by VimbaTheFish** [comment]
Sounds like a magick :0 I really don't see any connections with working config and other plugins and mods. I won't close this issue coz it can stop working anytime, and players could do the same stuff u did.

Looks like that's pixelmon issue, will investigate in that direction.

Contact me if it break again!

**Comment by Avesnis** [comment]
this error is happening to me when i change the first 3 days or add some. is there anyway to fix it?

![Untitled](https://user-images.githubusercontent.com/9434574/64634770-4450c580-d3bb-11e9-9f31-1184b48d908c.png)

thats the mods/plugins im using
